# Generated by Django 6.0.4 on 2026-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='party_symbols/', verbose_name='Party Symbol (Image)'),
        ),
    ]
